[package]
name = "anno"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = "0.14.0"
clap = "3.0.14"
slint = "0.2.0"
poppler = "0.3.1"

[build-dependencies]
slint-build = "0.2.0"
